# Generated by Django 2.0.6 on 2018-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180703_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_AREA',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
