# Generated by Django 2.0.7 on 2018-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180703_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='DATE',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='DETAILS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='HOSTS_ID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='POSTS_ID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='STATUS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='DATE',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='DETAILS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='HOSTS_ID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='PROTS_ID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='SCAN_TYPE',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='STATUS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='EQPT_DESC',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='EQPT_STATUS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='IDC_NAME',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='IPADDR',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='OPERATOR',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PRODUCT_NAME',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_MANAGER',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_NAME',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_PERSON_IN_CHARGE',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_PERSON_IN_CHARGE_TEL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_PERSON_IN_CHARGE_WECHAT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='PROVINCE_NAME',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ports',
            name='POSTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ports',
            name='POSTS_DESC',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ports',
            name='RULE_ID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
