# Generated by Django 2.0.7 on 2018-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180703_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='PROJ_PERSON_IN_CHARGE_TEL',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ports',
            name='POSTS',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
